version: '3.8'

services:
  ethereum:
    image: ethereum/client-go:stable
    container_name: geth
    restart: unless-stopped
    ports:
      - "30303:30303/tcp"      # P2P port
      - "30303:30303/udp"      # P2P port
      - "8545:8545"            # HTTP RPC
      - "8546:8546"            # WebSocket
    volumes:
      - geth-data:/root/.ethereum
    command:
      - --mainnet                 # Use mainnet (remove for testnet)
      - --http                    # Enable HTTP-RPC server
      - --http.addr=0.0.0.0      # Listen on all interfaces
      - --http.api=eth,net,web3   # Enable basic APIs
      - --http.vhosts=*          # Allow all virtual hosts
      - --ws                     # Enable WebSocket-RPC server
      - --ws.addr=0.0.0.0       # Listen on all interfaces
      - --syncmode=snap         # Use snap sync mode
      - --metrics               # Enable metrics
      - --maxpeers=50          # Limit peers for lighter resource usage
      - --cache=4096           # 4GB cache for better performance

  consensus:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    restart: unless-stopped
    depends_on:
      - execution
    ports:
      - "9000:9000/tcp"      # P2P port
      - "9000:9000/udp"      # P2P port
      - "5052:5052"          # HTTP API
    volumes:
      - lighthouse-data:/root/.lighthouse
    command:
      - lighthouse
      - beacon_node
      - --network=mainnet
      - --execution-endpoint=http://execution:8551
      - --http
      - --http-address=0.0.0.0
      - --metrics
      - --validator-monitor-auto
      - --checkpoint-sync-url=https://mainnet.checkpoint.sigp.io  # Fast sync

  mongodb:
    image: mongo:latest
    container_name: my-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  cdb:
    build:
      context: ./collect-blockchain-data
      dockerfile: Dockerfile
    environment:
      - MONGODB_URL=mongodb://localhost:27017
      - ETHERSCAN_API_KEY=
      - ETHEREUM_NODE_URL=
      - MORALIS_API_KEY=
    restart: unless-stopped

networks:
  default:
    name: ethereum-node
    driver: bridge
